Traceback (most recent call last):
  File "batch.py", line 283, in <module>
    a = semibatch(gas, surf, t_in, pressure, volume, ratio_in)
  File "batch.py", line 134, in semibatch
    sim.advance(time)  # Advance the simulation to next set time
  File "interfaces/cython/cantera/reactor.pyx", line 926, in cantera._cantera.ReactorNet.advance (interfaces/cython/cantera/_cantera.cpp:68369)
cantera._cantera.CanteraError: 
***********************************************************************
CanteraError thrown by CVodesIntegrator::integrate:
CVodes error encountered. Error code: -4
At t = 29.3699 and h = 4.24376e-09, the corrector convergence test failed repeatedly or with |h| = hmin.

Components with largest weighted error estimates:
8: 316934
29: 0.0115464
12: 0.00747476
39: -0.000138392
16: -8.18198e-05
17: -7.29572e-05
19: -7.08358e-05
18: -6.99904e-05
25: -6.29926e-05
23: -6.28542e-05
***********************************************************************

